import type { PreviewScenario } from "./gradePreview.types";

export const PREVIEW_SCENARIOS: PreviewScenario[] = [
  {
    id: "english",
    levelKey: "auth.institution.school",
    tabKey: "preview.s1.tab",
    subjectKey: "preview.s1.subject",
    topicKey: "preview.s1.topic",
    taskKey: "preview.s1.task",
    answerKey: "preview.s1.answer",
    feedbackKey: "preview.s1.feedback",
    monospace: false,
    score: 8.5,
    seconds: 3.2,
    metrics: [
      { labelKey: "preview.metric.grammar", value: 7 },
      { labelKey: "preview.metric.vocabulary", value: 9 },
      { labelKey: "preview.metric.content", value: 9 },
    ],
  },
  {
    id: "calculus",
    levelKey: "auth.institution.university",
    tabKey: "preview.s4.tab",
    subjectKey: "preview.s4.subject",
    topicKey: "preview.s4.topic",
    taskKey: "preview.s4.task",
    answerKey: "preview.s4.answer",
    feedbackKey: "preview.s4.feedback",
    monospace: true,
    score: 7,
    seconds: 2.9,
    metrics: [
      { labelKey: "preview.metric.accuracy", value: 6 },
      { labelKey: "preview.metric.method", value: 8 },
      { labelKey: "preview.metric.format", value: 9 },
    ],
  },
  {
    id: "maths",
    levelKey: "auth.institution.school",
    tabKey: "preview.s2.tab",
    subjectKey: "preview.s2.subject",
    topicKey: "preview.s2.topic",
    taskKey: "preview.s2.task",
    answerKey: "preview.s2.answer",
    feedbackKey: "preview.s2.feedback",
    monospace: true,
    score: 6,
    seconds: 2.4,
    metrics: [
      { labelKey: "preview.metric.accuracy", value: 5 },
      { labelKey: "preview.metric.method", value: 8 },
      { labelKey: "preview.metric.format", value: 7 },
    ],
  },
  {
    id: "programming",
    levelKey: "auth.institution.university",
    tabKey: "preview.s5.tab",
    subjectKey: "preview.s5.subject",
    topicKey: "preview.s5.topic",
    taskKey: "preview.s5.task",
    answerKey: "preview.s5.answer",
    feedbackKey: "preview.s5.feedback",
    monospace: true,
    score: 8,
    seconds: 4.1,
    metrics: [
      { labelKey: "preview.metric.accuracy", value: 7 },
      { labelKey: "preview.metric.efficiency", value: 8 },
      { labelKey: "preview.metric.style", value: 9 },
    ],
  },
  {
    id: "physics",
    levelKey: "auth.institution.school",
    tabKey: "preview.s3.tab",
    subjectKey: "preview.s3.subject",
    topicKey: "preview.s3.topic",
    taskKey: "preview.s3.task",
    answerKey: "preview.s3.answer",
    feedbackKey: "preview.s3.feedback",
    monospace: true,
    score: 5.5,
    seconds: 2.1,
    metrics: [
      { labelKey: "preview.metric.accuracy", value: 4 },
      { labelKey: "preview.metric.formula", value: 6 },
      { labelKey: "preview.metric.units", value: 8 },
    ],
  },
];
