import type { InstitutionType } from "../../lib/types";

export const INSTITUTION_SUGGESTIONS: Record<InstitutionType, string[]> = {
  SCHOOL: [
    "Qarshi shahridagi Prezident maktabi",
    "Qarshi shahar 1-son ixtisoslashtirilgan maktab-internati",
    "Qarshi shahar 1-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 2-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 3-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 4-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 5-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 6-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 7-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 8-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 9-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 10-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 12-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 15-umumiy o'rta ta'lim maktabi",
    "Qarshi shahar 20-umumiy o'rta ta'lim maktabi",
  ],
  UNIVERSITY: [
    "Qarshi davlat universiteti",
    "Qarshi davlat texnika universiteti",
    "Qarshi xalqaro universiteti",
    "Shahrisabz davlat pedagogika instituti",
    "Muhammad al-Xorazmiy nomidagi TATU Qarshi filiali",
    "Toshkent kimyo-texnologiya instituti Shahrisabz filiali",
    "Qarshi irrigatsiya va agrotexnologiyalar instituti",
    "Qarshi muhandislik-iqtisodiyot instituti",
    "Qarshi tibbiyot kolleji",
    "Qarshi transport kolleji",
  ],
  TUTORING: [
    "Registon o'quv markazi (Qarshi)",
    "SMART o'quv markazi (Qarshi)",
    "Level Up ingliz tili markazi (Qarshi)",
    "Super 30 o'quv markazi (Qarshi)",
    "Asliddin o'quv markazi (Qarshi)",
    "ALFA School (Qarshi)",
    "OXFORD BZT o'quv markazi (Qarshi)",
    "IT Park Qarshi o'quv markazi",
    "Najot Ta'lim (Qarshi)",
    "Xususiy repetitor",
  ],
};
