export enum ProfileMetric {
  GROUPS = "GROUPS",
  STUDENTS = "STUDENTS",
  LESSONS = "LESSONS",
  GRADED = "GRADED",
  MAJOR_MISTAKES = "MAJOR_MISTAKES",
  SUBMISSIONS = "SUBMISSIONS",
  MISTAKES = "MISTAKES",
  SUBJECTS = "SUBJECTS",
}
